### ISSUE TITLE
What does the 'cfg_map=8' mean? 

### ISSUE THREAD

**Issue by wuyuyu1024** [woctezuma/steam-stylegan2-ada-pytorch#1]
Hi, thanks for your work.
I'm confused what is the 'cfg_map=8' in your code? and how to use it?
And I also notice that 'cfg=auto_norp' and 'cifar_tune=1' are not included in the original code.
Could you give some annotation on those?

**Comment by woctezuma** [comment]
I mention these briefly [at the top othe README](https://github.com/woctezuma/stylegan2-ada-pytorch/tree/google-colab#changelog) of [my fork](https://github.com/woctezuma/stylegan2-ada-pytorch/tree/google-colab). Here is a quote:

> - add config `auto_norp` to replicate the `auto` config without EMA rampup,
> - allow to override mapping net depth with the command-line argument `--cfg_map`,
> - allow to enforce CIFAR-specific architecture tuning with the command-line argument `--cifar_tune`.

Basically, these arguments allow to override some of the parameters of the config.

If you look at the end of the paper, there is a table which I quoted [in this Github issue](https://github.com/NVlabs/stylegan2-ada/issues/3#issuecomment-708989797):

`--cfg_map` allows to override the value of the "mapping net depth", highlighted in yellow in the table below.

`--cifar_tune` allow to copy some of the settings (precisely the last 3 rows) in the "+Tuning" column at the right of the table.

`auto_norp` is the same as `auto`, but without EMA (Exponential Moving Average) rampup.

![article Fig 24](https://i.imgur.com/8VCMWPF.png)

**Keep in mind that you may not need all of these parameters!** The objective with these arguments is to make it easy to toggle these parameters ON/OFF, or to override their default value.

Personally, I have not yet settled for the optimal parameters for Steam banners, as I don't have much computing power to conduct experiments. So these arguments appear in the notebook to let you know that there is room for experiments!
